version: '3'
services:
  spring_boot:
    image: 
    ports: 
      - "8080:8080"
    depends_on: 
      - db

  db:
    image: mysql
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=true"
    ports: 
      - "3306:3306"

